### ISSUE TITLE
mongo is not up! error when executing v 0.0.6 on linux or windows

### ISSUE THREAD

**Issue by tpnykane** [milanaleksic/mongodiff#6]
prg/bin$ mongodiff-0.0.6-linux-amd64 -db onp_release -excludes scheduledservicecalls -fileOutput repurchase_
Mongo is not up!
toni@borkk:~/prg/bin$ 

0.0.3 works fine at the same time. The same goes for windows version.

**Comment by milanaleksic** [comment]
Sure your mongo I up in the background at the moment when the mongodiff is started?

**Comment by tpnykane** [comment]
Yes listening to localhost running in default port. And the same worked on version 0.0.3. (named 'mongodiff' below):

toni@borkk:~/prg/bin$ mongodiff-0.0.6-linux-amd64 -db foo -excludes bar -fileOutput test_
Mongo is not up!
toni@borkk:~/prg/bin$ mongodiff -db foo -excludes bar -fileOutput test_
Send SIGINT (Ctrl+C) when completed the introduction of things you wish to put in demo contents
^CSignal received: interrupt
No changes detected!

toni@borkk:~/prg/bin$ 

I tested this on linux when a colleague of mine reported a similar problem on windows.

**Comment by milanaleksic** [comment]
pretty dumb mistake, sorry for this; will re-release after re-verifying some basic flows to avoid again some other stupid mistake

**Comment by milanaleksic** [comment]
0.0.7 shouldn't have this problem any more
